### ISSUE TITLE
Primary key can't be changed after an object is inserted.

### ISSUE THREAD

**Issue by rexmas** [rexmas/RealmCrust#4]
Need to add a special case for Primary Keys.

**Comment by minuscorp** [comment]
Any update on this? I couldn't find any solution debugging the tests

**Comment by rexmas** [comment]
Ya, it was more difficult with my current structure than I thought. I came up with a design I think I like and will work on it in the next few days.

It will involve removing the `Mappable` protocol altogether and changing the property `primaryKeys` to `uniqueKeys` if that is fine with you.

FYI, at my current job we're moving towards both Realm and Swift, but it could be a while before we begin integrating Crust because it's an old large codebase with Core Data and Objective-C primarily - the transition will take some time. So it makes it a bit difficult to work on this during the work week presently. Just want to give you the heads up.

**Comment by minuscorp** [comment]
Hi!

Founding this repository gave me hope about a clean encoding and decoding using Realm, there a lot of choices out there but few of them supports relationships one-to-many and I think it's one of the huge advantages of this repository. We're starting as well to migrate all the old system with Core Data to Realm due to obvious reasons (the most important is that Core Data... :-1: ) and we're starting with the design of the architecture of the new code and models so I can wait some weeks to this to be fully finished and I'll try to help as much as we can if you want.

**Comment by rexmas** [comment]
That would be fantastic. If you start finding missing pieces feel free to open PRs and I'll get to them as quickly as possible. Much appreciated and thanks for the words of encouragement!

**Comment by rexmas** [comment]
This has lead me down a bit of a rabbit hole at the moment when it comes to nested objects with primary keys. I have some ideas about how to fix. May take a couple more nights to sort out.

**Comment by rexmas** [comment]
This should fix it https://github.com/rexmas/RealmCrust/commit/da6ef5264f4f75a1268ca3eb271b2ee19860445e

It's apart of https://github.com/rexmas/RealmCrust/pull/6

Sorry this took so long.

**Comment by minuscorp** [comment]
I'm taking a look into that, also into why that's not passing in the Travis CI...
